spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    kafka:
      bootstrap-servers: http://kafka:9093

odl:
  activeTxnBuffer: 45       #expressed in minutes

